distinct descriptor mode
torproject/onionbalance pull request #35
Opened 2020-07-28 15:42 UTC by zscole

2020-07-29 12:46 UTC, asn-d6 requested changes
Thanks for all the code!

I have a bunch of questions about your work:
1) How can I test that this feature works as intended? How did you test it yourself?
2) What's the logic behind the distinct descriptor mode? How does it work exactly? This should be a documentation inside the code (and also on the OBv3 docs but I can do that myself after I understand how it works).
3) How many introduction points can this now support at max?
4) Can you please make a unittest that demonstrates that the introduction points got distributed properly to the various descriptors?
5) Seems like the branch has conflicts with master, and also CI is broken.

Thanks again :)

2020-07-29 12:46 UTC, asn-d6 commented on onionbalance/hs_v3/params.py
> +MAX_INTRO_POINTS=10
Hmm, where did this 10 value come from? Can you consistently fit 10 intro points in a descriptor? If yes, let's change the name to `MAX_INTRO_POINTS_PER_DESCRIPTOR` and document it appropriately.

2020-07-29 12:46 UTC, asn-d6 commented on onionbalance/hs_v3/service.py
> +    def _get_intros_for_distinct_desc(self, maxCount=10):
Nitpick: `maxCount` is camel cased, when the rest of the code is underscore-based. Let's make all new code use underscores please.

2020-07-29 12:46 UTC, asn-d6 commented on onionbalance/hs_v3/service.py
> +        # logger.info("We got %d intros from %d instances. We want %d intros ourselves (got: %d)",
This log message got removed but it was useful. We should reinstall it somewhere.

2020-07-29 12:46 UTC, asn-d6 commented on onionbalance/hs_v3/service.py
> +        distinct_descriptors = params.DISTINCT_DESCRIPTORS
I like the idea of using distinct descriptors only when it's needed, so I really like the logic here. In this case, let's not make distinct descriptors be a global parameter, and let's just have this logic here to decide whether to enable this feature or not.

We don't need to expose this "distinct descriptor" feature to the user, and onionbalance can just intelligently decide whether to enable it or not. I like this.

2020-07-29 12:46 UTC, asn-d6 commented on onionbalance/hs_v3/service.py
> +        if distinct_descriptors:
Hm. I don't quite understand the logic here. Can you please move this to a new function and document how this distinct descriptors feature should work?

2020-07-29 12:46 UTC, asn-d6 commented on onionbalance/hs_v3/service.py
> +        else:
So this is the non-distinct descriptor mode? is this identical to the previous functionality of Onionbalance?
In any case, let's move this also to its own function and document how it works.

2020-07-30 18:34 UTC, zscole commented
Sorry for delayed response. Your patience is appreciated. Will have follow-up PRs submitted over the weekend. Excited to be contributing to this project!

2020-11-03 14:19 UTC, asn-d6 commented
Unfortunately I don't see this PR going anywhere. I close it. Feel free to reuse the code to do something good,.

2020-11-03 14:19 UTC, closed without merging

2020-12-19 23:51 UTC, artembokhan commented
Could anybody comment why the bakend limit is 20 in DD mode for v3?

ps. PR is working

2020-12-20 21:01 UTC, asn-d6 commented
> Could anybody comment why the bakend limit is 20 in DD mode for v3?
> 
> ps. PR is working

There is no DD mode in Onionbalance right now. This PR was left incomplete and far from done.

This code needs more work, and a decent final result can scale to any number of services.